---
- name: Create and run a nginx container with podman
  hosts: all
  gather_facts: yes
  tasks:
    - name: run nginx
      containers.podman.podman_container:
        name: nginx
        image: docker.io/library/nginx:latest
        state: started
        ports:
          - "8080:80" 
